import {
  TITLE_TEXT_STYLE,
  SCROLL_LIST,
  ADD_BUTTON,
  ROUND
} from '../commonStyles.js'

export const TITLE_PATTERN = ROUND.TITLE_PATTERN
export const SMALL_TITLE_PATTERN_TOP = ROUND.SMALL_TITLE_PATTERN_TOP
export const NUMBER_VALUE = ROUND.NUMBER_VALUE
export const TIPS_TEXT_STYLE = ROUND.TIPS_TEXT_STYLE
export { TITLE_TEXT_STYLE, SCROLL_LIST, ADD_BUTTON }
