import {
  TITLE_TEXT_STYLE,
  SCROLL_LIST,
  SQUARE,
  OPERATION_BUTTON, 
  BALANCE_VALUE,
  NEW_BALANCE_VALUE,
  BUTTON_IMG,
  TITLE_PATTERN_REFACTOR
} from '../commonStyles.js'

export const TITLE_PATTERN = SQUARE.TITLE_PATTERN
export const SMALL_TITLE_PATTERN_TOP = SQUARE.SMALL_TITLE_PATTERN_TOP
export const LINE = SQUARE.LINE
export { TITLE_TEXT_STYLE, SCROLL_LIST, OPERATION_BUTTON, BALANCE_VALUE, NEW_BALANCE_VALUE, BUTTON_IMG, TITLE_PATTERN_REFACTOR }
