import {
  TITLE_TEXT_STYLE,
  SCROLL_LIST,
  ADD_BUTTON,
  ROUND,
  OPERATION_BUTTON,
  BALANCE_VALUE, 
  NEW_BALANCE_VALUE,
  BUTTON_IMG,
  TITLE_PATTERN_REFACTOR
} from '../commonStyles.js'

export const TITLE_PATTERN = ROUND.TITLE_PATTERN
export const SMALL_TITLE_PATTERN_TOP = ROUND.SMALL_TITLE_PATTERN_TOP
export const NUMBER_VALUE = ROUND.NUMBER_VALUE
export const TIPS_TEXT_STYLE = ROUND.TIPS_TEXT_STYLE
export const LINE = ROUND.LINE
export { TITLE_TEXT_STYLE, SCROLL_LIST, ADD_BUTTON, OPERATION_BUTTON, BALANCE_VALUE, NEW_BALANCE_VALUE, BUTTON_IMG, TITLE_PATTERN_REFACTOR }
