import {
  TITLE_TEXT_STYLE,
  SCROLL_LIST,
  ADD_BUTTON,
  SQUARE,
  BALANCE_VALUE
} from '../commonStyles.js'

export const TITLE_PATTERN = SQUARE.TITLE_PATTERN
export const SMALL_TITLE_PATTERN_TOP = SQUARE.SMALL_TITLE_PATTERN_TOP
export const LINE = SQUARE.LINE
export { TITLE_TEXT_STYLE, SCROLL_LIST, ADD_BUTTON, BALANCE_VALUE }
