import {
  TITLE_TEXT_STYLE,
  SCROLL_LIST,
  ADD_BUTTON,
  ROUND,
  BALANCE_VALUE
} from '../commonStyles.js'

export const TITLE_PATTERN = ROUND.TITLE_PATTERN
export const SMALL_TITLE_PATTERN_TOP = ROUND.SMALL_TITLE_PATTERN_TOP
export const TIPS_TEXT_STYLE = ROUND.TIPS_TEXT_STYLE
export const LINE = ROUND.LINE
export { TITLE_TEXT_STYLE, SCROLL_LIST, ADD_BUTTON, BALANCE_VALUE }
